# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Oleksii Sidorov"

author:
  facebook:         acecreamu
  #youtubeUser:      your-id
  youtubeChannel:   OleksiiSidorov
  #twitter:          your-id
  github:           acecreamu
  #stackoverflow:    your-id
  #quora:            your-id
  linkedin:         sidorovoleksii
  #pinterest:        your-id
  #googlePlus:       your-id
  instagram:        acecreamu
  #reddit:           your-id
  #medium:           your-id
  #tumblr:           your-id
  email:            acecreamu@gmail.com

copyright:
  year:             2020
  name:             Oleksii Sidorov

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "sidorov_oleksii"

# URL
url:              "https://acecreamu.github.io/blog"
baseurl:          "/"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Los_Angeles
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Home"
    url:            "https://acecreamu.github.io"
  - name:           "About me"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  #- name:           "Github"
  #  url:            "https://github.com/AWEEKJ/Kiko-plus"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
